
name: Homebrew Swap deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [synchronize]

jobs:
  build-lint-test-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
      REACT_APP_GOOGLE_MAPS_URI: ${{ secrets.REACT_APP_GOOGLE_MAPS_URI }}
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2
    #set up Node
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    #install and lint backend
    - name: install and lint backend
      run: |
        npm install
        npm run lint
      working-directory: ./server
    #create .env for frontend build to include maps key in build
    - name: create .env for frontend build
      run: | 
        echo REACT_APP_GOOGLE_MAPS_API_KEY=$REACT_APP_GOOGLE_MAPS_API_KEY >> .env
      working-directory: ./client
    #install, lint, build front-end, then move to backend dir to serve
    - name: install, lint, build  frontend and move build-dir to backend-dir
      run: |
        npm install
        npm run lint
        npm run build:mv
      working-directory: ./client
    #run e2e tests (location field broken in CI environment so skipping 1 spec)
    - name: run full e2e tests
      uses: cypress-io/github-action@v2
      with:
        start: npm run start:server
        wait-on: 'http://localhost:3001/api/test/health'
        working-directory: client
        spec: |
          cypress/integration/homepage.spec.js
          cypress/integration/login.spec.js
          cypress/integration/my-offers.spec.js
          cypress/integration/pw-reset.spec.js
          cypress/integration/register.spec.js
    #deploy to Heroku staging app
    - name: deploy to staging
      if: ${{ github.event_name == 'push' }}
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: staging-homebrew-swap
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        #healthcheck: https://staging-homebrew-swap.herokuapp.com/api/test/health
        #rollbackonhealthcheckfailed: true
        appdir: server
      env:
        HD_JWT_SECRET: ${{ JWT_SECRET }}
        HD_SG_EMAIL_SENDKEY: ${{ SG_EMAIL_SENDKEY }}
        HD_MONGODB_URI: ${{ MONGODB_URI }}
    #run simple tests on staging
    - name: simple tests on staging
      if: ${{ github.event_name == 'push' }}
      uses: cypress-io/github-action@v2
      with:
        working-directory: client
        spec: cypress/live/live.spec.js
        config: baseUrl=https://staging-homebrew-swap.herokuapp.com
    #bump version
    - name: Bump version and push tag
      if: ${{ github.event_name == 'push' }}
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
          
        







