# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Homebrew Swap lint, test, deploy

on:
  push:
    branches:
      - main

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2
    #set up Node
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    #install, lint backend
    - name: install and lint backend
      run: |
        npm install
        npm run lint:fix
      working-directory: ./server
    #install, lint front-end
    - name: install, lint, build frontend
      run: |
        npm install
        npm run lint:fix
      working-directory: ./client
    #run e2e tests
    - name: run e2e tests
      uses: cypress-io/github-action@v2
      with:
        command: npm run test
        start: |
          npm run start
          npm run start:server
        wait-on: 'http://localhost:3000, http://localhost:3001/api/test/health'
        working-directory: client
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SG_EMAIl_SENDKEY: ${{ secrets.SG_EMAIL_SENDKEY }}
        TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}







