# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Homebrew Swap lint, build, test, deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    #set up Node
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    #frontend install and start
    - name: npm install, start
      run: |
        npm install
        npm run start
      working-directory: ./client



