
name: Homebrew Swap deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [synchronize]

jobs:
  build-lint-test-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2
    #set up Node
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    #create .env for frontend build to include maps key in build
    - name: create .env for frontend build
      run: | 
        echo REACT_APP_GOOGLE_MAPS_API_KEY=$REACT_APP_GOOGLE_MAPS_API_KEY >> .env
      working-directory: ./client
    #install, lint front-end, move to back-end folder to be served for tests
    - name: install, lint front-end
      run: |
        npm install
        npm run lint
        npm run build:mv
      working-directory: ./client
    #install and lint backend
    - name: install, lint, build back-end
      run: |
        npm install
        npm run lint
      working-directory: ./server
    #run e2e tests (location field broken in CI environment so skipping 1 spec)
    - name: run full e2e tests
      uses: cypress-io/github-action@v2
      with:
        start: npm run start:server
        wait-on: 'http://localhost:3001/api/test/health'
        working-directory: client
        spec: |
          cypress/integration/homepage.spec.js
          cypress/integration/login.spec.js
          cypress/integration/my-offers.spec.js
          cypress/integration/pw-reset.spec.js
          cypress/integration/register.spec.js
    #deploy front-end to Azure
    - name: deploy front-end to azure
      if: ${{ github.event_name == 'push' }}
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_SKY_0D2570103 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: '/client' # App source code path
        ###### End of Repository/Build Configurations ######
      env:
        REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}


    #deploy back-end to Heroku 
    - name: deploy back-end to Heroku
      if: ${{ github.event_name == 'push' }}
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: homebrew-swap
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: server
        healthcheck: https://homebrew-swap.herokuapp.com/api/test/health
        rollbackonhealthcheckfailed: true
    #bump version
    - name: Bump version and push tag
      if: ${{ github.event_name == 'push' }}
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
          
        







